In [2]:
import pandas as pd

In [3]:
import numpy as np

In [19]:
with open ('top10.cs') as f:
    top = f.read()

FileNotFoundError: [Errno 2] No such file or directory: 'top10.cs'

In [20]:
df= pd.read_csv('top10s.csv', encoding="latin1")

In [21]:
ls

Untitled.ipynb  top10s.csv

In [22]:
df.head(5)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,14,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,43,221,2,4,78

In [27]:
df.columns

Index(['Unnamed: 0', 'title', 'artist', 'top genre', 'year', 'bpm', 'nrgy',
       'dnce', 'dB', 'live', 'val', 'dur', 'acous', 'spch', 'pop'],
      dtype='object')

In [33]:
df.sort_values(by=['artist', 'top genre'])
df.sort_values(by='artist', ascending=True)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
31,32,My First Kiss - feat. Ke$ha,3OH!3,dance pop,2010,138,89,68,-4,36,83,192,1,8,62
229,230,She Looks So Perfect,5 Seconds of Summer,boy band,2014,160,95,49,-4,33,44,202,0,13,71
249,250,Say Something,A Great Big World,neo mellow,2014,138,15,45,-9,9,9,229,87,3,61
21,22,Whataya Want from Me,Adam Lambert,australian pop,2010,186,68,44,-5,6,45,227,1,5,66
37,38,If I Had You,Adam Lambert,australian pop,2010,131,91,65,-4,37,79,228,1,11,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,428,True Colors,Zedd,complextro,2016,126,79,57,-3,10,49,225,40,4,51
487,488,Get Low (with Liam Payne),Zedd,complextro,2017,108,93,72,-4,5,54,205,3,5,66
132,133,We Are Young (feat. Janelle Monáe),fun.,baroque pop,2012,184,64,38,-6,8,74,251,2,8,63
122,123,Some Nights,fun.,baroque pop,2012,108,74,67,-7,9,39,277,2,5,72
173,174,#thatPOWER,will.i.am,dance pop,2013,128,61,80,-6,7,40,280,0,6,68